### PR TITLE
Now possible to pass in soundfonts URL root and preferred audio file extension

### PR DESCRIPTION
**Pull request by benwiley4000**
One more.. this commit doesn't break existing uses, but does allow users to specify an alternative soundfont URL root and preferred file extension (mp3) if they wish, in the `Soundfont` constructor.

E.g.

`var soundfont = new Soundfont(new AudioContext(), 'https://cdn.example.com/soundfonts/', 'mp3');`

Of course, it's up to the user to figure out if the passed file root and extension actually produce the file they want. There's no fallback if the URL doesn't work! Using the constructor as normal (passing only an AudioContext) should work fine, though, as long as the git repo persists.

We're using this because we prefer to play mp3s, and to host the soundfonts on our own CDN (for extra precaution; we don't want our sounds to go missing!). It would also allow users to use their own soundfonts, if they wish.

### CODE REVIEW

**Comment by danigb** [comment]
Hi Ben,

Thanks for the pull request. Currently there is a mechanism to override the default CDN or sound format. It's described here: https://github.com/danigb/soundfont-player#configuration 

I suppose this is not very visible or well explained, or maybe this is not the optimal mechanism for overriding. Let me know what you think.

Saludos

**Comment by benwiley4000** [comment]
Actually, that's great. Thanks for that -- I'll just close this request. Would you be able to push the current commit to npm?

**Comment by danigb** [comment]
Done! Thanks

**Comment by danigb** [comment]
Hi @benwiley4000, after some thought, I decided to change the name to url generation configuration mechanism. I've opened an issue for that (#8). Some feedback will be very welcomed.

**Pull request closed without merging**
